### ISSUE TITLE
Время приготовления рецепта

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#11]
Время изначально учитывалось в дизайне интерфейса, но про него как-то забыли. Надо исправить.

**Comment by SID37** [comment]
Так, я сделал заглушку для времени для фронтэнда, можешь делать вьюшку, чем потом заполнять это поле-заглушку, потом придумаем

**Comment by SID37** [comment]
Пока конечный вариант - Время хранить в минутах, передавать, как структурку с тремя полями: минуты, часы, дни
