### ISSUE TITLE
Preview рецепта

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#14]
- [x] Переделать согласно новому дизайну
- [x] Не учтены случаи с слишком большим текстом описания/кол-вом ингредиентов - должны появляться многоточия. Вроде для этого есть css свойство overflow.
Каркас, скорее всего, сильно менять не придётся. Порядок секций их их содержимое - да.
Где оно лежит:
Views/Recipes/_Preview.cshtml
Styles/_recipe.scss 
Ответвляться от ветки dev-remake_main_page (именно ответвиться, а не в ней работать)
Для ингредиентов ввести классы, отвечающие за стиль для тех, что есть, и тех, что отсутствуют в инвентаре. Они будут выставляться в скриптах. Аналогично с рецептами.

**Comment by SID37** [comment]
Теперь во вьюшку Views/Recipe/_Preview.cshtml в качестве модели попадает не Recipe, а UserRecipe, в поддержку идеологии, что объекты из бд должны оставаться в недрах бэкенда, у UserRecipe в общем поля те жи, но добавлено поле CookingTime типа string, а поле Ingredients типа List<UserIngredient> (а не List<Ingredient>), а с ним проще работать - не надо скакать по таблицам

**Comment by SID37** [comment]
Теперь CookingTime это структурка(на самом деле класс), который содержит три целочисленных поля - Minutes, Hours и Days, я даже весьма колхозно запихнул их во вьюшку, но потестить сойдёт

**Comment by RobolabGs2** [comment]
Примерный дизайн (кнопка добавления в избранное точно изменится)
![image](https://user-images.githubusercontent.com/32936783/52181752-97034700-2806-11e9-917f-8ad6f3f21bf7.png)
