### ISSUE TITLE
Обработка not found при отображении картинки рецепта

### ISSUE THREAD

**Issue by SID37** [SID37/CraftBook#23]
- [x] Обработать not found при отображении картинки рецепта
Что бы не было вот такого
![default](https://user-images.githubusercontent.com/33577875/51852026-38d1f200-2336-11e9-8bcb-ade6fa352084.PNG)

**Comment by RobolabGs2** [comment]
А это разве не backendовская задача? Вы там можете отследить, есть картинка или нет, и слать заглушку вместо неё

**Comment by SID37** [comment]
Но ведь картинка - ссылка, и может быть и на стороннем сайте

**Comment by RobolabGs2** [comment]
Тогда опиши, что должно отображаться при отсутствии картинки? Чем тебя не устраивает текущий вариант?

**Comment by SID37** [comment]
Очевидно, некоторая дефолтная картинка
