### ISSUE TITLE
Нарисовать интерфейс

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#24]
- [x] главная страница #27 
- [x] создание рецепта #28 
- [x] просмотр рецепта #29 
- [x] ошибки #32
- [ ] профиль#30 
- [ ] настройки #31 
- [ ] регистрация/вход #33

**Comment by nosurprises13** [comment]
[xd.zip](https://github.com/SID37/CraftBook/files/2846036/xd.zip)

**Comment by RobolabGs2** [comment]
Так как пользователь переведён в разряд "будущее", отрисовка его интерфейса уходит в другую задачу
