### ISSUE TITLE
Нарисовать интерфейс: главная страница

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#27]
- [x] список рецептов
- [x] поиск по строке
- [x] инвентарь
- [x] кнопка входа/выхода в аккаунт

**Comment by nosurprises13** [comment]
![custom 1](https://user-images.githubusercontent.com/46989167/52183040-0122e880-2815-11e9-80d3-751fa632b47e.png)
![web 1366 1](https://user-images.githubusercontent.com/46989167/52183041-01bb7f00-2815-11e9-98fe-01ed42f21e7e.png)

**Comment by nosurprises13** [comment]
Вариант с кнопкой для авторизированных пользователей. По идее, можно ввести перечень ингредиентов и:
1) нажать на лупу = найти рецепт по введенным ингредиентам
2) нажать на "Создать рецепт", в итоге будет открываться страница создания рецепта с теми ингредиентами, которые были выбраны пользователем.  

![custom 1](https://user-images.githubusercontent.com/46989167/52183562-fd459500-2819-11e9-8e97-650028affbb4.png)

**Comment by nosurprises13** [comment]
Все иконки с главной страницы
[icons2.zip](https://github.com/SID37/CraftBook/files/2832348/icons2.zip)
