### ISSUE TITLE
Нарисовать интерфейс: создание рецепта

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#28]
Рецепт состоит из:

- названия
- описания
- инструкции
- аватарки
  - поле для ссылки (вводится ссылка/кидается в поле файл, он подгружается на сервер и появляется ссылка)
  - картинка, которая лежит по ссылке
- ингредиентов (можно приспособить под это инвентарь с главной страницы)
- времени
  - дни
  - часы
  - минуты

**Comment by nosurprises13** [comment]
Что-то такое, но:
1) каким образом пользователь будет вводить время?
2) должна ли появляться картинка рецепта на этой странице, или достаточно только поля для неё?

![web 1366 2](https://user-images.githubusercontent.com/46989167/52185135-2facbd80-282d-11e9-8d62-cb151793863d.png)

**Comment by RobolabGs2** [comment]
Картинка пусть лучше отображается.
Для времени должно быть три поля: дни, часы, минуты. Можно посмотреть на страницу создания, которая уже есть, там вроде всё поля работают

**Comment by nosurprises13** [comment]
![web 1366 2](https://user-images.githubusercontent.com/46989167/52340804-ca6ded80-2a21-11e9-9e68-c5e06b57fdd1.png)
![web 1366 3](https://user-images.githubusercontent.com/46989167/52340805-ca6ded80-2a21-11e9-9349-5f0e9a954935.png)
