### ISSUE TITLE
Нарисовать интерфейс: регистрация/вход

### ISSUE THREAD

**Issue by RobolabGs2** [SID37/CraftBook#33]
Тут есть несколько вариантов

1. **Отдельными страницами** - тыкаем на кнопку входа/регистрации, открывается полноценное окно
2. **Всплывающее окошко** - мини-окошко в центре страницы
3. **Выпадающее окошко** - тыкаем на кнопку -> из неё выпадает менюшка
4. **Комбинации вариантов** - для входа одно, для регистрации - другое

Поля
- Ник
- Почта
- Пароль

Стоит потеребить backendеров насчёт полей

**Comment by nosurprises13** [comment]
![artboard 3](https://user-images.githubusercontent.com/46989167/52511003-4bd6a300-2c0f-11e9-8f32-bc46e423f27e.png)
